columns = [
    'name',
    'game_id',
    'game_type',
    'isOrange',
    'won',
    'average hit distance',
    'ball hit forward',
    'dribbles',
    'passes',
    'time close to ball',
    'time closest to ball',
    'time furthest from ball',
    'time behind ball',
    'time in front ball',
    'time high in air',
    'time low in air',
    'time on ground',
    'time in defending third',
    'time in neutral third',
    'time in attacking third',
    'time in defending half',
    'time in attacking half',
    'time in corner',
    'time most forward player',
    'time between players',
    'time most back player',
    'time near wall',
    'time in front of center of mass',
    'time behind center of mass',
    'speed',
    'possession time',
    'turnovers',
    'turnovers on my half',
    'turnovers on their half',
    'wasted collection',
    'num small boosts',
    'num large boosts',
    'boost ratio',
    'used boost efficiency',
    'turnover efficiency',
    'shot %',
    'useful/hits',
    'time at boost speed',
    'time at slow speed',
    'time at super sonic',
    'boost usage',
    'num stolen boosts',
    'time low boost',
    'time no boost',
    'collection boost efficiency',
    'total boost efficiency',
    'aerial efficiency',
    'aerials',
]